remote_theme: pages-themes/cayman@v0.2.0

name: pages.d-sato.net
description: doewのブログ
url: https://pages.d-sato.net

future: true # JSTとUTCの違いか何かでうまくいかないので

github:
  is_project_page: false

layouts_dir: _layout
layout: default_
